---
title: "Data Import"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import a dataset

```{r}
litters_df = 
  read.csv("data_import_examples/data_import_examples/FAS_litters.csv")
```

Next step: Skiming data

```{r}
skimr::skim(litters_df)
```

Fix the missingness

```{r}
litters_df = 
  read.csv("data_import_examples/data_import_examples/FAS_litters.csv", na=c("NA",".",""),skip = 10)
```

Import Pups data

```{r}
pups_df =
  read_csv("data_import_examples/data_import_examples/FAS_pups.csv",
           skip = 3,
           na = c("NA",".","")
           )
#Janitor-- a package to clean the column name
pups_df = 
  janitor::clean_names(pups_df)
```

Import excel file

```{r}
mib_df = 
  read_excel("data_import_examples/data_import_examples/mlb11.xlsx")
```

import LotR word counts

```{r}
lotr_df = 
  read_excel("data_import_examples/data_import_examples/LotR_Words.xlsx", range = "B3:D6")
```

import the PULSE data

```{r}
pulse_df = 
  read_sas("data_import_examples/data_import_examples/public_pulse_data.sas7bdat")
```

